---
sudo: false
addons:
  coverity_scan:
    project:
      description: Build submitted via Travis CI
      name: maxmind/geoip-api-c
    notification_email: dev-ci@maxmind.com
    build_command_prepend: ./configure; make clean
    build_command: make -j 4
    branch_pattern: .*coverity.*
language: c
compiler:
  - clang
  - gcc
env:
  global:
    secure: |-
      bMDurejTvGTXwVcD/fTij5xkhqOzwHSFQHxP1tLGBfemvRQ/FgX2E2M8rWaD
      KbgKCgTSNB7fKtAvkFP+uteJ3/RY4HrQxlkY4/lG6tqlYJDCyLjxC0LLU5GE
      hfW0iiu9ozNtJzQ2A2O3mgTUmN4+ay25VMTfoAYALvT67qpW+NM=
before_script:
  - ./bootstrap
  - CFLAGS="-Wall -Wextra -Werror -Wno-unused-parameter" ./configure
  - make
script:
  - make check
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "WfyHKjt7GkS4U1tFmleDAwXEcs99LW33Gp0p8OwIPaV8ZI7WXZTw1ClJwr+Bpa9TDgfl26HX6IBcgX4ef/SAGvfLkYdEK8czYA2iT7VRudNQb/2oXdlwFz3hgY7yaROohkUgjo+IMq2efWFix7Z149ynex2k78Qp5g4GdZOLz48=\n"
